# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160410_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='category',
            field=models.CharField(choices=[(b'Academics', b'Academics'), (b'Dining', b'Dining'), (b'Housing and Facilities', b'Housing and Facilities'), (b'Services', b'Services'), (b'Student Activities', b'Student Activities'), (b'General', b'General')], max_length=30),
        ),
    ]
